FROM ghcr.io/mlflow/mlflow:v2.20.2

# Installer les dépendances pour PostgreSQL
RUN pip install psycopg2-binary boto3

# Vérifier l'installation
RUN python -c "import psycopg2; print('✅ psycopg2 installé avec succès')"