# dvc.yaml
stages:

  preprocess:
    cmd: poetry run python pricing_epac/preprocessing/full_preprocess.py
    deps:
      - pricing_epac/preprocessing/full_preprocess.py
      - data/raw/concateneRAHMA4.xlsx
    outs:
      - data/processed/pricing_fully_cleaned.xlsx

  train:
    cmd: poetry run python pricing_epac/models/train_and_compare.py
    deps:
      - pricing_epac/models/train_and_compare.py
      - data/processed/pricing_fully_cleaned.xlsx
      - pricing_epac/models/cover_size_pipeline.pkl          # si tu l'utilises encore
    outs:
      - models/