# config/mappings.yaml
siren:
  TLG: CENGAGE
  NGL: CENGAGE
  CLM: CENGAGE

text_color:
  "1": "1/1"
  "1/C": "1/1"
  "1C": "1/1"
  "4": "4/4"
  "4/C": "4/4"
  "4C": "4/4"

cover_finish_type:
  LGLOSS: LAYFLAT-GLOSS
  LAYFLAT GLOSS: LAYFLAT-GLOSS
  LMATT_SF: LAYFLAT MATTE SCUFF-FREE
  LAYFLAT MATTE SCUFF-FREE: LAYFLAT MATTE SCUFF-FREE
  LMATTE: LAYFLAT-MATTE
  MATT: MATT

cover_color:
  "4/C": "4/4"
  "4C": "4/4"
  "40": "4/0"
  "41": "4/1"
  "0": "0/0"
  "00": "0/0"


binding_type:
  LOOSELEAF_NO_COVER: LOOSELEAF-NC
  CASEBOUND: CASEBIND
  CASEBINDENDSHEET: CASEBIND-ES
  CASEBOUND-ES: CASEBIND-ES
  COILHARDTAB: COILHARD-TAB
  CARD: CARD
  PERFECT-NC: PERFECT-NC
  SADDLESTITCH: SS
  SADDLE STITCH: SS

cover_paper_type:
  100_GLOSSTEXT: 100_GLOSS_TEXT
  100_GLOSS_TEXT: 100_GLOSS_TEXT
  "100_GLOSSTEXT\t": 100_GLOSS_TEXT
  80_GLOSS_TEXT: 80_GLOSS_TEXT
  80_GLOSSTEXT: 80_GLOSS_TEXT
  80_GLOSSCOVER: 80_GLOSS_COVER

head_and_tail:
  BLACK & WHITE: BLACK & WHITE
  BLACK/WHITE: BLACK & WHITE
  WHITE/WHITE: WHITE
  WHITE: WHITE
  NONE: NONE

priority_level:
  HIGH: HIGH1
  HIGH*: HIGH1
  HIGH**: HIGH2

status:
  NEW: NEW
  ACCEPTED: ACCEPTED
  PENDING: PENDING
  PROOF OUT: PROOF_OUT
  ONPROD: ON_PROD
  READY: READY
  DELIVERED: DELIVERED
  PARTIAL DELIVERED: PARTIAL DELIVERED
  INVOICED: INVOICED
  COMPLETE: COMPLETE
  CANCELLED: CANCELLED
  CANCELED: CANCELLED
  ONHOLD: ON_HOLD

label_location:
  ES PAGE 2/BOTTOM/RIGHT: OTHER
  NONE: NONE
  SEE SAMPLE: OTHER
  LABEL LOCATION MXTST: OTHER

label_type:
  NONE: NONE
  STANDARD: STANDARD
  YES: STANDARD
  ISBN: ISBN
  ISBN-ST: ISBN
  "978-0-357-37403-0": ISBN
  BAR CODE: ISBN
  NO (IF BAR CODE LABEL): ISBN
  ADVANCE COPY (SILVER): OTHER
  FLORIDA: OTHER
  RELX: OTHER
  "2": OTHER
  GRADE 1: OTHER
  GRADE 2: OTHER
  GRADE 3: OTHER
  GRADE 4: OTHER
  GRADE 5: OTHER
  GRADE K: OTHER
  LABEL TYPE MXTST: OTHER

case_finish_type:
  NONE: NONE
  LAYFLAT-GLOSS: LAYFLAT-GLOSS
  LAYFLAT MATTE: LAYFLAT-MATTE
  LAYFLAT MATTE SCUFF-FREE: LAYFLAT MATTE SCUFF-FREE
  GLOSS FILM: GLOSS-FILM
  GLOSS-FILM: GLOSS-FILM
  LAYFLAT GLOSS: LAYFLAT-GLOSS

case_paper_type:
  NONE: NONE
  100_GLOSSTEXT: 100_GLOSS_TEXT
  10PT_C1S: 10PT_C1S
  16PT_C1S: 16PT_C1S

coil_type:
  NONE: NONE
  METAL: METAL
  METAL WHITE: METAL
  PLASTIC: PLASTIC
  PLASTIC BLACK: PLASTIC
  PLASTIC WHITE: PLASTIC
  BLACK PLASTIC: PLASTIC
  "1/C": PLASTIC
  "4/C": PLASTIC

tab_lamination:
  NONE: NONE
  MYLAR: MYLAR
  YES: LAYFLAT-GLOSS
  NO: NONE
  LAYFLAT-GLOSS: LAYFLAT-GLOSS
  LAYFLAT GLOSS: LAYFLAT-GLOSS
  GLOSS-FILM: GLOSS-FILM

tab_paper_type:
  NONE: NONE
  10PT_C2S: 10PT_C2S
  12PT_C2S: 12PT_C2S
  10PT_C1S: 10PT_C1S
  100_GLOSSTEXT: 100_GLOSS_TEXT